// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(HumanVZombiesDbContext))]
    partial class HumanVZombiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Domain.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Player", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("biteCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("game_id")
                        .HasColumnType("int");

                    b.Property<int?>("gameid")
                        .HasColumnType("int");

                    b.Property<bool>("is_human")
                        .HasColumnType("bit");

                    b.Property<bool>("is_patient_zero")
                        .HasColumnType("bit");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int?>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("gameid");

                    b.HasIndex("userid");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebAPI.Models.Domain.Player", b =>
                {
                    b.HasOne("WebAPI.Models.Domain.Game", "game")
                        .WithMany()
                        .HasForeignKey("gameid");

                    b.HasOne("WebAPI.Models.Domain.User", "user")
                        .WithMany()
                        .HasForeignKey("userid");

                    b.Navigation("game");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
